/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/FooterBar`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/components/profileCard`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/members`; params?: Router.UnknownInputParams; } | { pathname: `/members/components/CountPill`; params?: Router.UnknownInputParams; } | { pathname: `/members/components/EmptyState`; params?: Router.UnknownInputParams; } | { pathname: `/members/components/MemberCard`; params?: Router.UnknownInputParams; } | { pathname: `/members/components/MemberFormModal`; params?: Router.UnknownInputParams; } | { pathname: `/members/components/MembersHeader`; params?: Router.UnknownInputParams; } | { pathname: `/members/components/theme`; params?: Router.UnknownInputParams; } | { pathname: `/plans`; params?: Router.UnknownInputParams; } | { pathname: `/plans/components/PlanModal`; params?: Router.UnknownInputParams; } | { pathname: `/subscription`; params?: Router.UnknownInputParams; } | { pathname: `/subscription/whatsappTemplates`; params?: Router.UnknownInputParams; } | { pathname: `/subscription/components/Card`; params?: Router.UnknownInputParams; } | { pathname: `/subscription/components/Modal`; params?: Router.UnknownInputParams; } | { pathname: `/verify-otp`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/FooterBar`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/components/profileCard`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/members`; params?: Router.UnknownOutputParams; } | { pathname: `/members/components/CountPill`; params?: Router.UnknownOutputParams; } | { pathname: `/members/components/EmptyState`; params?: Router.UnknownOutputParams; } | { pathname: `/members/components/MemberCard`; params?: Router.UnknownOutputParams; } | { pathname: `/members/components/MemberFormModal`; params?: Router.UnknownOutputParams; } | { pathname: `/members/components/MembersHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/members/components/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/plans`; params?: Router.UnknownOutputParams; } | { pathname: `/plans/components/PlanModal`; params?: Router.UnknownOutputParams; } | { pathname: `/subscription`; params?: Router.UnknownOutputParams; } | { pathname: `/subscription/whatsappTemplates`; params?: Router.UnknownOutputParams; } | { pathname: `/subscription/components/Card`; params?: Router.UnknownOutputParams; } | { pathname: `/subscription/components/Modal`; params?: Router.UnknownOutputParams; } | { pathname: `/verify-otp`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/FooterBar${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard/components/profileCard${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/members${`?${string}` | `#${string}` | ''}` | `/members/components/CountPill${`?${string}` | `#${string}` | ''}` | `/members/components/EmptyState${`?${string}` | `#${string}` | ''}` | `/members/components/MemberCard${`?${string}` | `#${string}` | ''}` | `/members/components/MemberFormModal${`?${string}` | `#${string}` | ''}` | `/members/components/MembersHeader${`?${string}` | `#${string}` | ''}` | `/members/components/theme${`?${string}` | `#${string}` | ''}` | `/plans${`?${string}` | `#${string}` | ''}` | `/plans/components/PlanModal${`?${string}` | `#${string}` | ''}` | `/subscription${`?${string}` | `#${string}` | ''}` | `/subscription/whatsappTemplates${`?${string}` | `#${string}` | ''}` | `/subscription/components/Card${`?${string}` | `#${string}` | ''}` | `/subscription/components/Modal${`?${string}` | `#${string}` | ''}` | `/verify-otp${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/FooterBar`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/components/profileCard`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/members`; params?: Router.UnknownInputParams; } | { pathname: `/members/components/CountPill`; params?: Router.UnknownInputParams; } | { pathname: `/members/components/EmptyState`; params?: Router.UnknownInputParams; } | { pathname: `/members/components/MemberCard`; params?: Router.UnknownInputParams; } | { pathname: `/members/components/MemberFormModal`; params?: Router.UnknownInputParams; } | { pathname: `/members/components/MembersHeader`; params?: Router.UnknownInputParams; } | { pathname: `/members/components/theme`; params?: Router.UnknownInputParams; } | { pathname: `/plans`; params?: Router.UnknownInputParams; } | { pathname: `/plans/components/PlanModal`; params?: Router.UnknownInputParams; } | { pathname: `/subscription`; params?: Router.UnknownInputParams; } | { pathname: `/subscription/whatsappTemplates`; params?: Router.UnknownInputParams; } | { pathname: `/subscription/components/Card`; params?: Router.UnknownInputParams; } | { pathname: `/subscription/components/Modal`; params?: Router.UnknownInputParams; } | { pathname: `/verify-otp`; params?: Router.UnknownInputParams; };
    }
  }
}
